name: Alternative Ruby Engines

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ragdoll_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-version: "jruby-10.0.0.1"
            name: "JRuby 10.0.0.1 (Java 21)"
          - ruby-version: "truffleruby"
            name: "TruffleRuby"

    name: ${{ matrix.name }}
    env:
      RAGDOLL_POSTGRES_HOST: localhost
      RAGDOLL_POSTGRES_USER: postgres
      RAGDOLL_POSTGRES_PASSWORD: postgres
      RAGDOLL_POSTGRES_PORT: 5432
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test
