name: CRuby (MRI)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ragdoll_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["3.2", "3.3", "3.4"]

    name: Ruby ${{ matrix.ruby-version }}
    env:
      RAGDOLL_POSTGRES_HOST: localhost
      RAGDOLL_POSTGRES_USER: postgres
      RAGDOLL_POSTGRES_PASSWORD: postgres
      RAGDOLL_POSTGRES_PORT: 5432
    steps:
      - uses: actions/checkout@v4
      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y libmagickwand-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
